stages:
  - productions
  
production:
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=${REPO_NAME} --api-key${HEROKU_API_KEY}
  only:
    - develop
  tags:
    - "docker"
