export const GET_LOGIN_BEGIN = "GET_LOG_IN_BEGIN";
export const GET_LOGIN_SUCCESS = "GET_LOG_IN_SUCCESS";
export const GET_LOGIN_FAIL = "GET_LOG_IN_FAIL";
export const REGISTER_BEGIN = "REGISTER_BEGIN"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const SIGNUP_BEGIN = "SIGNUP_BEGIN"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const PAGINATION_BEGIN = "PAGINATION_BEGIN";
export const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
export const PAGINATION_FAIL = "PAGINATION_FAIL";

export const GET_ORDER_BEGIN = "GET_ORDER_BEGIN"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const GET_RECIPE_BEGIN = "GET_RECIPE_BEGIN"
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS"
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL"

export const GET_RECIPE_DETAILS_BEGIN = "GET_RECIPE_DETAILS_BEGIN"
export const GET_RECIPE_DETAILS_SUCCESS = "GET_RECIPE_DETAILS_SUCCESS"
export const GET_RECIPE_DETAILS_FAIL = "GET_RECIPE_DETAILS_FAIL"

export const PATCH_PROFILE_BEGIN = "PATCH_PROFILE_BEGIN"
export const PATCH_PROFILE_SUCCESS = "PATCH_PROFILE_SUCCESS"
export const PATCH_PROFILE_FAIL = "PATCH_PROFILE_FAIL"

export const GET_USER_BEGIN = "GET_USER_BEGIN"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"