export const GET_LOG_IN_BEGIN = "GET_LOG_IN_BEGIN";
export const GET_LOG_IN_SUCCESS = "GET_LOG_IN_SUCCESS";
export const GET_LOG_IN_FAIL = "GET_LOG_IN_FAIL";

export const POST_LOG_IN_BEGIN = "POST_LOG_IN_BEGIN";
export const POST_LOG_IN_SUCCESS = "POST_LOG_IN_SUCCESS";
export const POST_LOG_IN_FAIL = "POST_LOG_IN_FAIL";

export const PAGINATION_BEGIN = "PAGINATION_BEGIN";
export const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
export const PAGINATION_FAIL = "PAGINATION_FAIL";
