export const LOGIN_BEGIN = "LOGIN_BEGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_BEGIN = "REGISTER_BEGIN"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const PAGINATION_BEGIN = "PAGINATION_BEGIN";
export const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
export const PAGINATION_FAIL = "PAGINATION_FAIL";


export const GET_ORDER_BEGIN = "GET_ORDER_BEGIN"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const GET_RECIPE_BEGIN = "GET_RECIPE_BEGIN"
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS"
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL"

export const GET_RECIPE_DETAILS_BEGIN = "GET_RECIPE_DETAILS_BEGIN"
export const GET_RECIPE_DETAILS_SUCCESS = "GET_RECIPE_DETAILS_SUCCESS"
export const GET_RECIPE_DETAILS_FAIL = "GET_RECIPE_DETAILS_FAIL"
